// Generated by CoffeeScript 1.4.0
(function() {
  var app;

  app = angular.module('twentyone', []);

  app.controller("GameCtrl", function($scope) {
    return $scope.demo = "It is working, just need to manually bootstrap the app";
  });

  angular.bootstrap(document, ["twentyone"]);

}).call(this);
